Dcokerを使ってdecomojiをインストール
decomoji/slack-reaction-decomoji pull request #53
Opened 2019-06-21 10:16 UTC by NextatNishizawa

素晴らしい、Slackの絵文字をありがとうございます。  
ローカルの環境を汚したくないmacユーザー(私)のために、Dockerでインストールできる環境を作成しました。  
よろしければ、使ってください。

2019-06-21 10:23 UTC, kubosho requested changes
全体的に良さそうです。細かいところを直していただけると助かります。

2019-06-21 10:23 UTC, kubosho commented on INSTALLATION.md
> +Docker-compose up -d
先頭が大文字になっているようです。

2019-06-21 10:23 UTC, kubosho commented on INSTALLATION.md
> +Docker run -it slack-reaction-decomoji_app bash
先頭が大文字になっているようです。

2019-06-21 11:58 UTC, NextatNishizawa commented
@kubosho 
ご確認ありがとうございます。
指摘箇所修正いたしました。

2019-06-21 12:03 UTC, kubosho approved these changes

2019-06-21 12:03 UTC, kubosho commented
@NextatNishizawa LGTM

2019-07-02 06:54 UTC, oti commented
@NextatNishizawa PRsありがとうございます！
これ、Dockerfileとdocker-compose.ymlを `script/` に入れられますか？

2019-07-04 05:33 UTC, NextatNishizawa commented
> @NextatNishizawa PRsありがとうございます！
> これ、Dockerfileとdocker-compose.ymlを `script/` に入れられますか？

@oti 
docker-composeのマウントがdocker-compose.ymlファイルより上のディレクトを指定できないので難しいです。

2019-07-08 04:05 UTC, merged

2019-07-08 04:36 UTC, kubosho commented
やるとしたら `docker-compose.yml` はリポジトリルートに残しておいて、Dockerfileは別ディレクトリに置くという形ですね。

2019-07-08 04:38 UTC, oti commented
最初は気になってたんだけど、デコモジファイル自体とは直接関係ないpackage.jsonもルートに置かれているから、これがいいならDockerfileもいいよな、という気持ちで今はいます。

2019-07-08 04:39 UTC, kubosho commented
それは
そうだ